# Generated by Django 3.0.5 on 2020-07-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantaty',
            field=models.IntegerField(default=1),
        ),
    ]
