# Generated by Django 3.0.5 on 2020-07-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200728_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantaty',
            field=models.IntegerField(default=0),
        ),
    ]
